### ISSUE TITLE
Dictionary changes size during iteration (probably on rebuild)

### ISSUE THREAD

**Issue by gtfierro** [gtfierro/ontoenv#14]
```
Traceback (most recent call last):
  File "/Users/user/repositories/Brick/generate_brick.py", line 1025, in <module>
    env.refresh()
  File "/Users/user/repositories/Brick/brickvenv/lib/python3.10/site-packages/ontoenv/__init__.py", line 98, in refresh
    for uri, filename in self.mapping.items():
RuntimeError: dictionary changed size during iteration 
```

**Comment by gtfierro** [comment]
Fixed in recent commit
